### ISSUE TITLE
Basic example failing with 401

### ISSUE THREAD

**Issue by pkakelas** [standard-crypto/farcaster-js#410]
**Describe the bug**
Hey there, I'm trying to run the basic example and it seems that it fails with a 401 HTTP code. 
Am I missing anything? Thank you in advance! 

**To Reproduce**
1. Run the following code: 

```
import { MerkleAPIClient } from "@standard-crypto/farcaster-js";
import { ethers } from "ethers";

const wallet = new ethers.createRandom();
const client = new MerkleAPIClient(wallet);

const main = async () => {
	// by username
	await client.lookupUserByUsername("dwr");
}
main()

**Comment by gsgalloway** [comment]
Ah yes, the problem here would be that you cannot use any random wallet. You would need to use a wallet backing an existing, registered Farcaster user. The Merkle APIs enforce that (nearly) all queries must be authenticated by an existing user, so that they can more intelligently apply rate limits.

Recommend that you grab a copy of the private key or mnemonic registered to your Farcaster user for use in authenticating to the platform. In the app, this can be found within settings -> Recovery Phrase

**Comment by Kstar0722** [comment]
@gsgalloway can you provide link for register farcaster user?
