### ISSUE TITLE
Notification type `cast-mention` and `cast-reply` doesn't have `content.cast` type

### ISSUE THREAD

**Issue by vinliao** [standard-crypto/farcaster-js#459]
**Describe the bug**
I fetched notification with `v2MentionAndReplyNotificationsGet()`, and filter out the notification where type is `cast-mention` and `cast-reply`. The `farcaster-js` type for that data doesn't have the `content.cast` field.

**To Reproduce**
1. `const notifications = v2MentionAndReplyNotificationsGet()`
2. `notifications.map(notification => notification.content.cast)`
3. TypeScript throws error, that's a valid data returned from Merkle's Hub

**Expected behavior**
Type in `farcaster-js` should have the `content.cast` field.

**Screenshots**
![Screenshot from 2023-01-12 18-56-49](https://user-images.githubusercontent.com/34117807/212062131-2b487c31-e3fb-4f12-a969-5818889368dc.png)
![Screenshot from 2023-01-12 18-57-45](https://user-images.githubusercontent.com/34117807/212062140-9d8768b1-97b7-4ee0-9fff-6ecedcb7e01c.png)
![Screenshot from 2023-01-12 18-58-10](https://user-images.githubusercontent.com/34117807/212062145-ba32abcf-058a-41dc-b3ce-e59741bdbc58.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, macOS 11.4]
 - Node version [e.g 16.4.2]
 - Code Version [e.g. 1.1.0]

**Additional context**

**Comment by gsgalloway** [comment]
Ah ok, I see. Looks like the issue is that that endpoint is returning the generic `Notification` type, when it can and should be narrowed to the more specific type `NotificationCastMention  | NotificationCastReply`

Also, can I ask what your use case is that you're using the swagger generated methods directly, rather than using the `MerkleAPIClient` class?

**Comment by vinliao** [comment]
Pretty new to this SDK (it's a great package, thank you), and I'm still stumbling around in trying to use it. This is how I generally use it right now:

```
const fc = new MerkleAPIClient(blablabla);
fc.apis.casts.v2CastsGet(blablabla);
```

It seems like you're suggesting this is not the recommended way to do it? Again, pretty new to this, still learning :)

**Comment by gsgalloway** [comment]
No problem! The lower-level swagger-generated methods are made available through `fc.apis`, but you shouldn't need to use them unless you're really customizing things.

Otherwise, check out [these methods](https://github.com/standard-crypto/farcaster-js/blob/develop/docs/classes/index.MerkleAPIClient.md#methods), in particular [fc.fetchMentionAndReplyNotifications()](https://github.com/standard-crypto/farcaster-js/blob/develop/docs/classes/index.MerkleAPIClient.md#fetchmentionandreplynotifications), which should be much easier for you to use as it abstracts away things like handling pagination in the response.

Separately, will push a patch release to deploy the fix for this issue

**Comment by vinliao** [comment]
Thank you!
